### ISSUE TITLE
Create BE service

### ISSUE THREAD

**Issue by elderanakain** [elderanakain/daily-dish#86]
### Requirements

- [x] Stores meals
- [x] Allows CRUD operations
- [x] Ktor

Server-side:
- [x] [Mock server](https://github.com/elderanakain/daily-dish-be/issues/1)

Client-side:

- [x] [Android side](https://github.com/elderanakain/daily-dish/issues/140)

### Tech info

- [x] [Ktor: Past, Present, and Future! by Hadi Hariri](https://www.youtube.com/watch?v=Ga_jUBj-sK0)
- [x] [Server-Side Development with Kotlin: Frameworks and Libraries](https://blog.jetbrains.com/kotlin/2020/11/server-side-development-with-kotlin-frameworks-and-libraries/)
